apiVersion: v1
kind: Namespace
metadata:
  name: graphql-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql
  namespace: graphql-system

spec:
  selector:
    matchLabels:
      app: graphql

  template:
    metadata:
      labels:
        app: graphql
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: graphql
          image: graphql-image

          ports:
            - name: graphql
              containerPort: 8080
            - name: graphql-debug
              containerPort: 8081

          # readinessProbe:
          #   httpGet:
          #     path: /query
          #     port: 8080
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   successThreshold: 1
          #   failureThreshold: 2
          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu

---
apiVersion: v1
kind: Service
metadata:
  name: graphql-service
  namespace: graphql-system

spec:
  selector:
    app: graphql
