apiVersion: v1
kind: Service
metadata:
  name: graphql-service
  namespace: graphql-system

spec:
  type: ClusterIP
  ports:
    - name: graphql
      port: 8080
      targetPort: graphql
    - name: graphql-debug
      port: 8081
      targetPort: graphql-debug
