apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql
  namespace: graphql-system

spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true

      containers:
        - name: graphql
          resources:
            requests:
              cpu: "250m"
            limits:
              cpu: "250m"
